
services:
  db:
    container_name: mysql-django
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql/db:/var/lib/mysql:rw"
      - "./mysql/log:/var/log/mysql:rw"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - "${SQL_PORT}:3306"

  web:
    image: docker-project:v33
    container_name: django-web
    build:
      #context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
    links:
      - db
